/**
 * 시안이 lucide UMD의 `data-lucide="kebab-name"` 방식이었으므로
 * 데이터에 남아 있는 kebab 이름을 그대로 쓰되, 번들 트리셰이킹을 위해
 * 실제로 사용하는 아이콘만 명시적으로 등록한다.
 */
import {
  AlertCircle,
  Armchair,
  ArrowRight,
  Award,
  BadgeDollarSign,
  Banknote,
  BarChart3,
  Bell,
  BookOpen,
  Building2,
  CalendarCheck,
  CalendarClock,
  CalendarDays,
  CalendarPlus,
  CalendarRange,
  Check,
  CheckCheck,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  ChevronUp,
  CircleDot,
  ClipboardList,
  Clock,
  Copy,
  CreditCard,
  DoorOpen,
  ExternalLink,
  FileSpreadsheet,
  FileText,
  Filter,
  FolderOpen,
  Footprints,
  Gauge,
  GitCompare,
  Flag,
  GraduationCap,
  History,
  Inbox,
  Info,
  LayoutDashboard,
  LayoutGrid,
  LineChart,
  Link as LinkIcon,
  ListChecks,
  ListOrdered,
  Lock,
  LogIn,
  LogOut,
  Mail,
  MapPin,
  Megaphone,
  Monitor,
  MessageCircle,
  MessageSquare,
  MessageSquareText,
  MessagesSquare,
  Pencil,
  Percent,
  PieChart,
  Plus,
  Presentation,
  Printer,
  QrCode,
  Receipt,
  RefreshCw,
  Repeat,
  Route,
  Save,
  ScanLine,
  Search,
  Send,
  Settings,
  Shield,
  ShieldCheck,
  ShieldOff,
  SlidersHorizontal,
  Smartphone,
  Sparkles,
  Star,
  Table2,
  Ticket,
  Timer,
  Trash2,
  TrendingDown,
  TrendingUp,
  TriangleAlert,
  Trophy,
  Upload,
  UserCheck,
  UserPlus,
  UserX,
  Users,
  Utensils,
  Wallet,
  X,
  Zap,
} from 'lucide-react'
import type { ComponentType, SVGProps } from 'react'

type IconComp = ComponentType<SVGProps<SVGSVGElement>>

const REGISTRY: Record<string, IconComp> = {
  'alert-circle': AlertCircle,
  armchair: Armchair,
  'arrow-right': ArrowRight,
  award: Award,
  'badge-dollar-sign': BadgeDollarSign,
  banknote: Banknote,
  'bar-chart-3': BarChart3,
  bell: Bell,
  'book-open': BookOpen,
  'building-2': Building2,
  'calendar-check': CalendarCheck,
  'calendar-clock': CalendarClock,
  'calendar-days': CalendarDays,
  'calendar-plus': CalendarPlus,
  'calendar-range': CalendarRange,
  check: Check,
  'check-check': CheckCheck,
  'chevron-down': ChevronDown,
  'chevron-left': ChevronLeft,
  'chevron-right': ChevronRight,
  'chevron-up': ChevronUp,
  'circle-dot': CircleDot,
  'clipboard-list': ClipboardList,
  clock: Clock,
  copy: Copy,
  'credit-card': CreditCard,
  'door-open': DoorOpen,
  'external-link': ExternalLink,
  'file-spreadsheet': FileSpreadsheet,
  'file-text': FileText,
  filter: Filter,
  flag: Flag,
  'folder-open': FolderOpen,
  footprints: Footprints,
  gauge: Gauge,
  'git-compare': GitCompare,
  'graduation-cap': GraduationCap,
  history: History,
  inbox: Inbox,
  info: Info,
  'layout-dashboard': LayoutDashboard,
  'layout-grid': LayoutGrid,
  'line-chart': LineChart,
  link: LinkIcon,
  'list-checks': ListChecks,
  'list-ordered': ListOrdered,
  lock: Lock,
  'log-in': LogIn,
  'log-out': LogOut,
  mail: Mail,
  'map-pin': MapPin,
  megaphone: Megaphone,
  monitor: Monitor,
  'message-circle': MessageCircle,
  'message-square': MessageSquare,
  'message-square-text': MessageSquareText,
  'messages-square': MessagesSquare,
  pencil: Pencil,
  percent: Percent,
  'pie-chart': PieChart,
  plus: Plus,
  presentation: Presentation,
  printer: Printer,
  'qr-code': QrCode,
  receipt: Receipt,
  'refresh-cw': RefreshCw,
  repeat: Repeat,
  route: Route,
  save: Save,
  'scan-line': ScanLine,
  search: Search,
  send: Send,
  settings: Settings,
  shield: Shield,
  'shield-check': ShieldCheck,
  'shield-off': ShieldOff,
  'sliders-horizontal': SlidersHorizontal,
  smartphone: Smartphone,
  sparkles: Sparkles,
  star: Star,
  'table-2': Table2,
  ticket: Ticket,
  timer: Timer,
  'trash-2': Trash2,
  'trending-down': TrendingDown,
  'trending-up': TrendingUp,
  'triangle-alert': TriangleAlert,
  trophy: Trophy,
  upload: Upload,
  'user-check': UserCheck,
  'user-plus': UserPlus,
  'user-x': UserX,
  users: Users,
  utensils: Utensils,
  wallet: Wallet,
  x: X,
  zap: Zap,
}

interface Props {
  name: string
  size?: number
}

export function Icon({ name, size = 16 }: Props) {
  const C = REGISTRY[name] ?? ClipboardList
  return <C width={size} height={size} />
}
